version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend-e2e
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: frontend-e2e
    ports:
      - "3000:3000"
    depends_on:
      - backend